# Generated by Django 4.0.3 on 2022-03-12 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eticket', '0002_alter_booking_no_of_bookings_alter_show_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('museum_name', models.CharField(max_length=40)),
                ('date_of_visit', models.DateField(max_length=20)),
                ('time_slot', models.TimeField(max_length=30)),
                ('no_of_bookings', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Show',
        ),
        migrations.AddField(
            model_name='visitor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone',
            field=models.IntegerField(max_length=12),
        ),
    ]
