# Generated by Django 4.0.3 on 2022-03-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eticket', '0003_booking_detail_delete_booking_delete_show_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking_detail',
            old_name='no_of_bookings',
            new_name='no_of_booking',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='visitor',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='nationality',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
